server:
  addr: ":8123"
  mode: "release"
  read_timeout: 30s
  write_timeout: 30s

redis:
  url: ""
  pool_size: 50

auth:
  admin_machine_user:
    pat: ""
  zitadel:
    issuer: ""
    client_id: ""
    client_secret: ""
    organization_id: ""
  cache_ttl: 5m
  header_keys:
    user_id: "X-Auth-Request-User"
    user_email: "X-Auth-Request-Email"
    user_groups: "X-Auth-Request-Groups"
    user_preferred_username: "X-Auth-Request-Preferred-Username"
    user_jwt: "X-Auth-Request-Access-Token"

observability:
  metrics_enabled: false
  trace_enabled: false
  tracing_endpoint_url: ""
  log_level: "info"
  log_format: "json"
  log_source: false